# -*- coding: utf-8 -*-
"""snowflake_create_session_summary_dag

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1852y-551GqbghVc__tN3JddAdxIWXCB9
"""

from airflow import DAG
from airflow.decorators import task
from airflow.providers.snowflake.hooks.snowflake import SnowflakeHook
from datetime import datetime

def return_snowflake_conn():
    # Initialize the SnowflakeHook using your connection ID
    hook = SnowflakeHook(snowflake_conn_id='snowflake_conn')
    return hook.get_conn().cursor()

# Step 2: ELT DAG for Creating a Joined Table
with DAG(
    dag_id='snowflake_create_session_summary_dag',
    start_date=datetime(2024, 10, 23),
    catchup=False,
    schedule_interval=None,
    tags=['ELT']
) as elt_dag:

    @task
    def create_session_summary():
        cur = return_snowflake_conn()
        try:
            # Create session_summary table by joining user_session_channel and session_timestamp
            cur.execute("""
                CREATE TABLE IF NOT EXISTS dev.analytics.session_summary AS
                SELECT
                    u.userId,
                    u.sessionId,
                    s.ts,
                    u.channel
                FROM
                    dev.raw_data.user_session_channel u
                JOIN
                    dev.raw_data.session_timestamp s
                ON
                    u.sessionId = s.sessionId
                WHERE
                    u.sessionId NOT IN (
                        SELECT sessionId FROM dev.analytics.session_summary
                    );
            """)
            print("session_summary table created successfully")
        finally:
            cur.close()

    create_session_summary()